### ISSUE TITLE
I am the developer of thunderdex. Possible team up

### ISSUE THREAD

**Issue by HiFIi** [Sgambe33/flutter_wt_wiki#1]
Hey dude. Would you want to team up and work on a war thunder wiki app?

**Comment by Sgambe33** [comment]
Hey there! Sure, I'll dm you on discord if you want

**Comment by HiFIi** [comment]
Yes please.  Hifii is my username

**Comment by HiFIi** [comment]
> Hey there! Sure, I'll dm you on discord if you want

Sorry for a reply 5 hrs later. Didn't expect you to reply so soon

https://discord.gg/sdVDNpYs
